# Generated by Django 5.2.1 on 2025-08-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
