# Generated by Django 5.2.1 on 2025-07-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Especie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='media/especies/'),
        ),
    ]
